require_relative 'openrgss/rgss'

require_relative 'openrgss/bitmap'
require_relative 'openrgss/color'
require_relative 'openrgss/font'
require_relative 'openrgss/plane'
require_relative 'openrgss/rect'
require_relative 'openrgss/sprite'
require_relative 'openrgss/table'
require_relative 'openrgss/tilemap'
require_relative 'openrgss/tone'
require_relative 'openrgss/viewport'
require_relative 'openrgss/window'
require_relative 'openrgss/rgsserror'
require_relative 'openrgss/rgssreset'

require_relative 'openrgss/audio'
require_relative 'openrgss/graphics'
require_relative 'openrgss/input'